### PR TITLE
update search tests to reflect dev updates

### PR DESCRIPTION
**Pull request by m8ttyB**
* Updated the POM to fall in line with the new DOM structure of the Super Search page
* Reorganized the code to group similar groupings of locators together
* Updated the tests to reflect the new behavior
* Added a few comments for readability

r? @stephendonner, @rbillings, and @peterbe

### CODE REVIEW

**Comment by stephendonner** [comment]
Even with --reruns=5, I'm getting a couple failures, one of which is (at least for the past 5 suite - not just test -- runs) persistent: TestSuperSearchLayout.test_default_fields_for_firefox

Since this is a refactoring, and the current test failures are tied to earlier code changes necessitating this, it's hard (for me, at least) to isolate whether this is a new failure.

Pastebin of my run here: http://pastebin.com/JV6v6Y0k

**Comment by m8ttyB** [comment]
Good catch - I missed a commit - the removal of a duplicate testcase.

I can't comment on the 2nd failure - `test_search_with_multiple_lines` - it passes for me.

**Comment by rbillings** [comment]
For me,  test_search_with_multiple_lines failed locally with unable to find element: cs_super.select_facet('0', 'release channel')

Test_layout failed locally & on Sauce with test_default_fields_for_firefox, unable to find: assert 'product' == cs_super.field('0')

Test layout also failed on Sauce for:
tests.test_layout.TestLayout.test_that_products_are_sorted_correctly
Executing: [find element: By.cssSelector: #homepage-graph .loading])
 Unable to locate element: {"method":"css selector","selector":"#homepage-graph .loading"}

I'll re-check after your next commit.

**Comment by m8ttyB** [comment]
@rbillings commit is landed. One note though, I didn't make a change to `test_that_products_are_sorted_correctly`.  That test is xfailed so I'm a bit surprised, though that error leads me to believe the wait for page to load locator needs to be tweaked.

**Comment by rbillings** [comment]
Test continues to fail locally with same error- does not repro on Sauce: test_search_with_multiple_lines  
unable to find element: cs_super.select_facet('0', 'release channel')

All other tests pass.

**Comment by m8ttyB** [comment]
Lovely and bizarre. I'll dig into the locator used that signifies page load.

**Comment by rbillings** [comment]
All tests now pass locally with the added wait statement.

**Comment by m8ttyB** [comment]
thanks @rbillings .. merging

**Pull request merged**
