### PR TITLE
Decommission

### PR DESCRIPTION
**Pull request by m8ttyB**
Decommission the Socorro-Tests repository.

The tests have successfully been moved into the [project repository](https://github.com/mozilla/socorro/tree/master/e2e-tests). [Jenkins jobs](https://webqa-ci.mozilla.com/view/Socorro/) have been updated and are passing. Now for the real work, greatly improving the test coverage.

[Merged mozilla/socorro](https://github.com/mozilla/socorro/pull/3480) pr.

Issue #405 should now be satisfied 💯 

/cc @peterbe, @willkg, and @adngdb

### CODE REVIEW

**Review by stephendonner — APPROVED** [review]
r+ and let me or @davehunt know if you need help or permissions to decom the rest of the list here: https://wiki.mozilla.org/QA/Execution/Web_Testing/Repositories#Deactivating_a_repository

**Comment by m8ttyB** [comment]
Thanks @stephendonner. woot woot.

**Comment by m8ttyB** [comment]
Travic-CI hooks removed. And marked as dormant on the wiki.

**Comment by davehunt** [comment]
Thanks @m8ttyB! I've also now done the following:
- [x] Change the owner in the repository's wiki page to "Web QA (dormant)"
- [x] Deactivate any of the Webhooks for/against the repository
- [x] Deactivate GitHub Issues for the repository
- [x] Deactivate requires.io for the repository

**Pull request merged**
