### PR TITLE
xfail layout test

### PR DESCRIPTION
**Pull request by m8ttyB**
A wee small regression was caught. xfailing the product list test.

### CODE REVIEW

**Comment by m8ttyB** [comment]
merging

**Comment by stephendonner** [comment]
Really confused as to what happened, here, but I'm behind for a number of reasons, this week, so bear with me.

1. The pull suspects https://github.com/mozilla/socorro/pull/3413 (but never appears to directly confirm, certainly not here), yet references -- in its commit -- https://github.com/mozilla/Socorro-Tests/pull/392/files#diff-816d4eb818b162660182e96fb4ba0181R13 - a bug "1292954" which is an invalid bug number
2. At no point does there actually appear to be pre-approval for or an r? sought for this change, which surely and hopefully would have caught the typo in the bug-number comment, at least.

I'm already going to start updating https://wiki.mozilla.org/Web_Testing/Automation/CodeReviewProcess (in an updated form, early next week) and related documentation, so anything we can learn from what's working/followed, and not -- and why, and what we can do about it, together -- would be greatly appreciated.

**Comment by stephendonner** [comment]
1) Le sigh - apologies, a bug in Nightly apparently truncated the last char of the highlighted string...I'm going to now investigate that more fully, instead, while still focusing on the much-needed Web QA doc update(s) I mentioned, re: https://wiki.mozilla.org/QA/Execution/Web_Testing/Automation (and related ilk).

2) I can't trust IRCCloud history any longer (ironically, since that's the whole point, and my Fluidapp.com-based one crashes on startup 100%, since OS X 10.12 beta (Sierra), but if there was a need an unanswered (or unmentioned approval, elsewhere) let's ensure that gets mentioned explicitly in the pull request, for future reference - makes; the digital paper trail that much easier.

**Comment by nthomas-mozilla** [comment]
Sorry for any process bustage on that PR. This appears to be strongly related to the test change you needed - https://bugzilla.mozilla.org/show_bug.cgi?id=1292594

**Comment by m8ttyB** [comment]
@stephendonner sorry for the confusion on your end. It was a small enough tweak that I had the dev team look over my shoulder for the r+. I'll endeavor to help layout a better paper trail in the future.

**Pull request merged**
